version: '3.3'
services:
    portainer-ee:
        ports:
            - '8000:8000'
            - '9443:9443'
        container_name: portainer
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/mnt/data/docker/portainer:/data'
        image: 'portainer/portainer-ee:latest'
