version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "$$2a$$10$$L.kxaQIbyN6Q5web2/4fRut3zIxReWFjxjc2mlA/k2PfZwYTagBVa"
      CF_SLUG: ""
      DEBUG: "TRUE"
      MEMORY: "4G"
      ICON: ""
      SPAWN_PROTECTION: "0"
      MOTD: ""
      OPS: ""
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/dockerdata/minecraft/server:/data
      - /mnt/dockerdata/minecraft/modpacks:/modpacks
